name: Auto Build & Deploy to Hostinger Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repo
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Setup Docker builder
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build image dari Dockerfile
      - name: Build Docker image
        run: docker build -t cms-app:latest .

      # Step 4: Upload image ke Hostinger (via SSH)
      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            script: |
              cd /root/cms-deploy
              git fetch --all
              git reset --hard origin/main
              docker compose down
              docker compose build
              docker compose up -d
